[package]
name = "shader-preview"
version.workspace = true
edition.workspace = true

[dependencies]
# Internal crates
void_math = { workspace = true }
void_render = { workspace = true }
void_asset_server = { workspace = true }

# Graphics
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }

# Utilities
env_logger = { workspace = true }
log = { workspace = true }
gltf = { workspace = true }
