[package]
name = "void_engine"
version.workspace = true
edition.workspace = true
description = "Metaverse Engine - orchestration and application framework"

[features]
default = ["hot-reload"]
hot-reload = ["void_asset/hot-reload", "void_core/hot-reload"]

[dependencies]
void_core = { workspace = true }
void_math = { workspace = true }
void_memory = { workspace = true }
void_structures = { workspace = true }
void_ecs = { workspace = true }
void_event = { workspace = true }
void_asset = { workspace = true }
void_render = { workspace = true }
void_graph = { workspace = true }
void_xr = { workspace = true }
void_ir = { workspace = true }
void_kernel = { workspace = true }
parking_lot = { workspace = true }
